<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_react-combobox-view-25</name>
   <tag></tag>
   <elementGuidId>337a9de1-6d61-467e-815d-6b23dbd6a554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' _vst_ ') and (position() = 7)]//*[@aria-haspopup = 'dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>._vst_:nth-child(7) [aria-haspopup=&quot;dialog&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f555359b-89b5-4978-81b0-2f121894d21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-combobox-view-25</value>
      <webElementGuid>0e317e8f-cc7d-4eaf-b11a-1551b2c500ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_kohvda-o_O-label_sgdv3c-o_O-labelDisabled_wt43vm</value>
      <webElementGuid>02a1fdfa-e37e-4184-bbc2-386d5361085e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8bfbd3d6-2a46-4b40-a7b5-a6bef13efc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e7b24ef-f23f-4bc1-875e-977568bcf5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>6202c203-1f58-4c16-b2f7-3ccf5e5183a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d1130fb-497b-4313-9389-25b980d124bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>react-combobox-view-25</value>
      <webElementGuid>6b53276e-e757-4e7b-9ce7-a74a12619f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9d6d0bf16198ec4e3ce93516c19fa766</value>
      <webElementGuid>e426c00f-3d0f-4824-be1e-5009dd791b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' _vst_ ') and (position() = 7)]//*[@aria-haspopup = 'dialog']</value>
      <webElementGuid>4dfcb99e-a4de-4d8c-93d6-ccdd72fe45a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KSR-6646/Page_Microsoft Dynamics 365/iframe_fullscreen-app-host</value>
      <webElementGuid>e9d2478e-ea25-4d6b-99d2-a2dc6abcb887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' _vst_ ') and (position() = 7)]//*[@aria-haspopup = 'dialog']</value>
      <webElementGuid>a8f6ea05-75c7-4749-b58b-faba5cb36314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-combobox-view-25' and (text() = 'react-combobox-view-25' or . = 'react-combobox-view-25')]</value>
      <webElementGuid>430dc7db-cc89-4eb7-a5ff-70f42c2c742a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
