<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2021</name>
   <tag></tag>
   <elementGuidId>08e2e1e1-a7bf-4fd9-8c19-343bdb9af333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 5)]//div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(5) div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b1443a04-5ec9-4fe7-bc8d-a41b1dc4b0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>itemTemplateContainer_n2n7f8</value>
      <webElementGuid>5739f7e5-6389-4bd9-b438-bff99844069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2021</value>
      <webElementGuid>c0289f30-1a84-40dd-819a-e6ba3260c69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>2021</value>
      <webElementGuid>88618114-c4ac-40f1-beae-2909e63f7fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-abf62302faaf448a61b798b237386832</value>
      <webElementGuid>d74fc92c-9742-44c2-80e2-1fe16d2790fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 5)]//div</value>
      <webElementGuid>5ac39251-1858-4520-97ae-d4fc7b2a750b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KSR-6646/Page_Microsoft Dynamics 365/iframe_fullscreen-app-host</value>
      <webElementGuid>d4159db9-2ced-413b-a31c-f173634dd9ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 5)]//div</value>
      <webElementGuid>a55ef908-2d9f-4e3f-bf87-7bf8245bf300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2021' or . = '2021')]</value>
      <webElementGuid>8077dee2-7734-45c3-ab41-fbac384aed01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
