<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_react-combobox-view-7-instructions</name>
   <tag></tag>
   <elementGuidId>360d22a7-e107-4f90-bbda-a85016663123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = 'react-combobox-view-7-instructions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;react-combobox-view-7-instructions&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b897d955-4b71-4046-99a9-8e39721eaaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b57fd642-6344-4481-a31d-8484c0e5e9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-combobox-view-7</value>
      <webElementGuid>81130c7e-b3c9-42c4-8fa6-c7b51932eb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_kohvda-o_O-label_187h95e</value>
      <webElementGuid>8207a32c-ae16-451d-8fb1-524f87f4f766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>60fbb4f4-75be-42cc-ba2e-31bba3b2b582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e99be42-1d3f-425a-b778-1f1c8fcdce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9c0503c6-83df-4166-9aca-ea08b7d2ba00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>7fe49d25-74e1-4d0e-a3b4-83666fbd6aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>react-combobox-view-7-instructions</value>
      <webElementGuid>86514629-afca-4f84-8010-58e241db17e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>react-combobox-view-7-instructions</value>
      <webElementGuid>f4090f70-54cc-40e9-a37c-44bf45e1691a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-155f17f70ae7030ecc403ecd3ed2a5ca</value>
      <webElementGuid>a95fb774-9113-4e57-ade3-728f3454c831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = 'react-combobox-view-7-instructions']</value>
      <webElementGuid>2fab4b75-a9b5-40ed-99b3-70d3a19fdf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KSR-6646/Page_Microsoft Dynamics 365/iframe_fullscreen-app-host</value>
      <webElementGuid>b03b1ca5-671b-41bc-9b42-168fa7f162ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = 'react-combobox-view-7-instructions']</value>
      <webElementGuid>fe0b8dc5-15e2-4ca9-95fd-7b06c4b505c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-combobox-view-7' and (text() = 'react-combobox-view-7-instructions' or . = 'react-combobox-view-7-instructions')]</value>
      <webElementGuid>e357d128-dd0e-4121-9e3c-c3d0d595b803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
