<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_AppLandingPage</name>
   <tag></tag>
   <elementGuidId>425d4e9f-884c-4d96-b4e7-038add689e89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'AppLandingPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AppLandingPage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;AppLandingPage&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3d632bc1-116a-4106-bc83-10dcc9dd9d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AppLandingPage</value>
      <webElementGuid>bd24a3eb-fa42-47e1-a18e-3980228bbaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AppLandingPage</value>
      <webElementGuid>cbc19ba6-c550-4d9e-a393-c69cefd853ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/%7b638755445720000190%7d/webresources/msdyn_appmanagementcontrol</value>
      <webElementGuid>543675f2-c4e9-4c10-aa94-d20649d5fecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-bh pa-cs pa-ck </value>
      <webElementGuid>0b7e3d0a-c35b-4c2b-99ef-5f72b785033b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AppLandingPage</value>
      <webElementGuid>1b5d4894-ecca-4a91-be60-47217792f4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-644b38da09716b0f1b8784c759ff015a</value>
      <webElementGuid>f6323c74-5a45-459b-8071-228430245a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'AppLandingPage']</value>
      <webElementGuid>7ecf63e8-3fd2-4535-9330-a5e6b97967d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'AppLandingPage']</value>
      <webElementGuid>7f5018e4-7983-40b6-a01f-61fe84dd1cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'AppLandingPage' and @title = 'AppLandingPage' and @src = '/%7b638755445720000190%7d/webresources/msdyn_appmanagementcontrol' and (text() = 'AppLandingPage' or . = 'AppLandingPage')]</value>
      <webElementGuid>41a3c933-0e21-499f-9628-5f311524a96c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
