<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_new_PrivatePage</name>
   <tag></tag>
   <elementGuidId>dc5fcf2b-f58c-4559-b778-4240d2710e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'FullPageWebResource']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FullPageWebResource</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;new_HomePage&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2ad00506-fea2-448b-a425-0e4e6d960e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FullPageWebResource</value>
      <webElementGuid>7fd79c58-5565-4ebe-abcc-88f1139d0c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>HomePage</value>
      <webElementGuid>1b126514-e6e0-4149-9627-ab11a4f0d6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>MscrmControls.WebResource.WebResourceHtmlControl-FullPageWebResource</value>
      <webElementGuid>9b1b9370-3764-45ff-976a-ef2b69dd79b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/%7b638755445720000190%7d/webresources/new_HomePage</value>
      <webElementGuid>8390c555-8fd2-4cbd-8623-f22d99e9c809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new_HomePage</value>
      <webElementGuid>07cac02f-b4d6-4dc8-8d9b-b4ed5b776356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-bu pa-f pa-gt </value>
      <webElementGuid>198f1349-f12a-4990-bd62-cb0d353d180a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>new_PrivatePage</value>
      <webElementGuid>2a988f01-12bb-4496-8d40-f27bb5971e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2e6fb0671fcbe8f3a68a1346c04de849</value>
      <webElementGuid>c018941f-bd18-4eff-9bb3-7a02069db0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'FullPageWebResource']</value>
      <webElementGuid>ffb60b04-e2e1-48ba-97bc-9eafabb84b2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'FullPageWebResource']</value>
      <webElementGuid>e1527776-51a3-42d5-903b-113c003996e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'FullPageWebResource' and @src = '/%7b638755445720000190%7d/webresources/new_HomePage' and @name = 'new_HomePage' and (text() = 'new_PrivatePage' or . = 'new_PrivatePage')]</value>
      <webElementGuid>6ffff3e5-4476-4dd0-9397-4b8fb3bffd73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
