<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_embeddedCanvasApp</name>
   <tag></tag>
   <elementGuidId>e0e6ae82-2a21-449f-8815-dd42b1418fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'embeddedCanvasApp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#embeddedCanvasApp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#embeddedCanvasApp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9599cc54-d8a9-45d2-b15b-f5c8d7a97726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>embeddedCanvasApp</value>
      <webElementGuid>72836267-3f19-4d68-a1ab-f60e560f3bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>embeddedCanvasApp</value>
      <webElementGuid>d0794ffd-dc23-4cdb-a940-80c931c6613b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ec856a708ecb0a0d810535ad1625a2de</value>
      <webElementGuid>fbff2cc0-a5a3-48d2-9d04-7f2e53666023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'embeddedCanvasApp']</value>
      <webElementGuid>ae0afe8e-8f33-431f-93e8-03a6751fae3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KSR-6646/Page_Microsoft Dynamics 365/iframe_new_PrivatePage</value>
      <webElementGuid>c8fb8a74-2736-48ba-9542-9a55321df1a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'embeddedCanvasApp']</value>
      <webElementGuid>96d2ab23-2294-47bc-9b4d-d3175ee3f58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'embeddedCanvasApp' and (text() = 'embeddedCanvasApp' or . = 'embeddedCanvasApp')]</value>
      <webElementGuid>d6f246f7-8c89-40d5-99f0-96e2b5b6bbbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
