<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_react-select-3-option-1</name>
   <tag></tag>
   <elementGuidId>413762de-1c62-45d2-9c5c-48e4f67ffd7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f7fb3571-2a35-4c46-8b60-2488a096a8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>50d349ad-2c4c-43f9-bb06-4fcda61b9348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c5a478dd-8f15-4dca-afcf-84dba516f14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c7a8b78c-a1fc-41e2-be42-1f5ddfa247cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>353fee5b-b67a-41f9-920d-a9d32387b523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_2lsolt-o_O-item_15nbabd-o_O-item_ncvfsf</value>
      <webElementGuid>2497db5d-44f3-417f-9da1-bfa8586eb574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f0edba2-1775-4ad3-875e-5e459e8f6153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>107bcb17-525c-43ad-8c03-cd46daa80c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>141</value>
      <webElementGuid>1c12079c-b2d7-4888-b575-f7719da04773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>react-select-3-option-1</value>
      <webElementGuid>76d00c43-90de-4cc7-b40d-1db0966b84a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>0cade237-57d0-4c8d-a73e-34963729567f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-33ec563863a589ce2dd1d47e50a025ff</value>
      <webElementGuid>3440e20b-8a73-441e-9aef-2ec01d2b9f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 2)]</value>
      <webElementGuid>4450dd9f-9f89-4231-a07c-64dbe64913a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KSR-6646/Page_Microsoft Dynamics 365/iframe_fullscreen-app-host</value>
      <webElementGuid>fe679377-bd90-4247-a382-c39bae85c855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 2)]</value>
      <webElementGuid>f9bac36c-d72f-40b3-9769-13ac8202e51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'react-select-3-option-1' or . = 'react-select-3-option-1')]</value>
      <webElementGuid>9410a226-983a-4196-9a80-7c49db56f2e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
