<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Accounts</name>
   <tag></tag>
   <elementGuidId>90441cdd-5005-4be2-9259-9c57e6195c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ChevronDown-symbol ') and (@title = 'Accounts')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.ChevronDown-symbol[title=&quot;Accounts&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Accounts&quot;i] >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a81fb9a8-93f2-40b6-8356-809165f3d776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>eafee457-c1fa-4565-8309-82782bc309cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Accounts</value>
      <webElementGuid>2260bc25-1af5-4376-bddc-5985db074c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>symbolFont ChevronDown-symbol pa-dx pa-dy pa-cl </value>
      <webElementGuid>f8c3c9af-ba0d-47dc-8e79-64efb100ce2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accounts</value>
      <webElementGuid>0e60d0c3-8131-4ecc-8559-87e2a2eb41c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0eb805eed7f2d6a22e74e18716d38568</value>
      <webElementGuid>8a25c9a9-240d-4f1f-9c2e-ba855511261f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ChevronDown-symbol ') and (@title = 'Accounts')]</value>
      <webElementGuid>8317e3bc-7bba-496a-b77d-6f47b7ceba1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ChevronDown-symbol ') and (@title = 'Accounts')]</value>
      <webElementGuid>09f64809-7917-4d20-9411-a91b2571661b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Accounts' and (text() = 'Accounts' or . = 'Accounts')]</value>
      <webElementGuid>b8f14bb1-c9f2-495f-8d96-5c021fefccfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
