<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New</name>
   <tag></tag>
   <elementGuidId>24fe4994-ce58-4357-9b80-b58e21491175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = 'id-741']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' pa-mt ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;id-741&quot;] .pa-mt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;New&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be4bae2d-54b2-4721-ae35-e25991b5b832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-dl pa-cr pa-mq pa-au pa-e pa-ex pa-mt pa-dm </value>
      <webElementGuid>0469788f-ed8f-4d8f-983c-a423ec1463c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>838f90bf-7ddd-44db-b96b-fbe9a0eedd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>1712c2bf-c1ed-4ab5-b130-c1390cd38dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-824a466950b1d088eef48e68edb962ba</value>
      <webElementGuid>1ff30546-080f-45fb-9d74-d687f36f0310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = 'id-741']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' pa-mt ')]</value>
      <webElementGuid>f13e0d91-3a13-46c7-b460-b6cf533df564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = 'id-741']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' pa-mt ')]</value>
      <webElementGuid>1ad2d9b1-ac23-424c-b843-0356e42e83a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'New' or . = 'New')]</value>
      <webElementGuid>62ce0560-8ee5-495f-8cc2-290ad9d7e921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
